version: '3'
services:
  skill-verifier:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DSTACK_SOCKET=/var/run/dstack.sock
    command: sh -c "apk add --no-cache docker-cli && npm install --production && node server.js"
    restart: unless-stopped
